//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vadimRabotaet.DALandDomain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Адрес> Адрес { get; set; }
        public virtual DbSet<Должность> Должность { get; set; }
        public virtual DbSet<Ед__измерения> Ед__измерения { get; set; }
        public virtual DbSet<Заказ> Заказ { get; set; }
        public virtual DbSet<Категоря_товров> Категоря_товров { get; set; }
        public virtual DbSet<Клиент> Клиент { get; set; }
        public virtual DbSet<ПодробностиЗаказа> ПодробностиЗаказа { get; set; }
        public virtual DbSet<Сотрудник> Сотрудник { get; set; }
        public virtual DbSet<Способ_оплаты> Способ_оплаты { get; set; }
        public virtual DbSet<Статус_заказа> Статус_заказа { get; set; }
        public virtual DbSet<Страна_произваодителя> Страна_произваодителя { get; set; }
        public virtual DbSet<Товар> Товар { get; set; }
        public virtual DbSet<Фирма> Фирма { get; set; }
    }
}
