//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vadimRabotaet.DALandDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказ()
        {
            this.ПодробностиЗаказа = new HashSet<ПодробностиЗаказа>();
        }
    
        public double Код { get; set; }
        public int КодСтатусаЗаказа { get; set; }
        public System.DateTime ДатаПродажи { get; set; }
        public int КодСпособаОплаты { get; set; }
        public string КодКлиента { get; set; }
        public double КодАдреса { get; set; }
        public byte[] ИзображениеШтрихКода { get; set; }
    
        public virtual Адрес Адрес { get; set; }
        public virtual Клиент Клиент { get; set; }
        public virtual Способ_оплаты Способ_оплаты { get; set; }
        public virtual Статус_заказа Статус_заказа { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПодробностиЗаказа> ПодробностиЗаказа { get; set; }
    }
}
