//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vadimRabotaet.DALandDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПодробностиЗаказа
    {
        public double Код { get; set; }
        public double КодЗаказа { get; set; }
        public double КодТовара { get; set; }
    
        public virtual Заказ Заказ { get; set; }
        public virtual Товар Товар { get; set; }
    }
}
