//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vadimRabotaet.DALandDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудник
    {
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public System.DateTime ДатаРождения { get; set; }
        public string НомерТелефона { get; set; }
        public double Адрес { get; set; }
        public Nullable<int> КодДолжности { get; set; }
    
        public virtual Должность Должность { get; set; }
    }
}
