//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vadimRabotaet.DALandDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товар
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товар()
        {
            this.ПодробностиЗаказа = new HashSet<ПодробностиЗаказа>();
        }
    
        public double Код { get; set; }
        public Nullable<double> артикул { get; set; }
        public string Наименование { get; set; }
        public int КодКатегории { get; set; }
        public double Цена { get; set; }
        public byte[] Изображение { get; set; }
        public Nullable<int> КодЕдиницыИзмерения { get; set; }
        public Nullable<System.DateTime> ДатаИзготовления { get; set; }
        public Nullable<System.DateTime> СрокомГодности { get; set; }
        public Nullable<int> КодФирмы { get; set; }
        public Nullable<int> КодСтраныПроизводителя { get; set; }
    
        public virtual Ед__измерения Ед__измерения { get; set; }
        public virtual Категоря_товров Категоря_товров { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПодробностиЗаказа> ПодробностиЗаказа { get; set; }
        public virtual Страна_произваодителя Страна_произваодителя { get; set; }
        public virtual Фирма Фирма { get; set; }
    }
}
